version: "3"

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - cache:/data
    networks:
      - default
  
  app:
    image: mbaoma/note-app
    #build:
      #context: .
      #dockerfile: Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///people.db
    ports:
      - "8080:8080"  
    depends_on:
      - sqlite3
    networks:
      - default

volumes:
  cache:
    driver: local

networks:
  default:
    driver: bridge