name: Publish Docker image
 
on: [push]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: Mbaoma/build-image@v1.4
        with:
          image_name: ${{ github.repository }} 
          github_token: ${{ secrets.GITHUB_TOKEN }}
