name: Publish Docker image
 
on: [push]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image using custom action
        uses: Mbaoma/build-image@v2.0

        with:
          image-name: ${{ github.repository }}
          dockerfile-path: 'Dockerfile'
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ github.sha }}

       
        # uses: glueops/build-image@v0.1.0
        # with:
        #   dockerfile-path: ../Dockerfile
        #   image-name: ${{ github.repository }}  # it will be lowercased internally
        #   registry: ghcr.io
        #   registry-username: ${{ github.actor }}
        #   registry-password: ${{ secrets.GITHUB_TOKEN }}
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   tags: ${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}



      