name: Publish Docker image
 
on: [push]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and Push Docker Image
        # uses: macbre/push-to-ghcr@master
        uses: Mbaoma/build-image@v3.0
        with:
          image_name: ${{ github.repository }} 
          # dockerfile-path: 'Dockerfile'
          # registry: ghcr.io
          # registry-username: ${{ github.actor }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # tags: ${{ github.sha }}
      