name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: base-note  

on:
  push:
    branches: [ main ]
  pull_request:
        branches:  [ main ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: swagger-api.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t swagger-api.azurecr.io/myapp:${{ github.sha }}
        docker push swagger-api.azurecr.io/myapp:${{ github.sha }}     

  deploy:
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'swagger-api.azurecr.io/myapp:${{ github.sha }}'

