name: CI/CD Pipeline - runs tests and deploys to Azure VM

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version:  3.11.1

      - name: Install Nginx
        run: |
          sudo apt update -y
          sudo apt install nginx -y

      - name: Install Dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install "connexion[swagger-ui]"
      
      #- name: Run tests
        #run: python3 -m pytest

# this job depends on the successful completion of the build job above
#   deploy:
#     permissions:
#       contents: none
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Development'

#     steps:
#       - name: Login to Azure
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Checkout source code
#         uses: actions/checkout@v3
      
#       - name:  Deploy to Azure VM
#         uses: appleboy/ssh-action@v0.1.7
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.KEY }}
#           port: ${{ secrets.PORT }}
#           script: |
#             sudo service nginx stop
#             sudo rm -r apis
#             git clone https://github.com/Mbaoma/python-rest-apis.git
#             sudo mv python-rest-apis apis
#             cd apis/Part_1
#             git pull origin main
#             sudo systemctl daemon-reload
#             sudo systemctl restart app.service
#             sudo systemctl start nginx
#             sudo systemctl restart nginx
            
      
      
    
      
      
     


