name: Publish Docker image
 
on: [push]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: macbre/push-to-ghcr@master
        # uses: Mbaoma/build-image@v2.0
        with:
          image_name: ${{ github.repository }} 
          # dockerfile-path: 'Dockerfile'
          # registry: ghcr.io
          # registry-username: ${{ github.actor }}
          # registry-password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # tags: ${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
      